### ISSUE TITLE
[New Snap] Web3 Security

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#101]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/AnChainAI/web3-security-snap
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/web3-security-snap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://github.com/MetaMask/snaps-registry/issues/101#issuecomment-1709431717
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue? https://github.com/MetaMask/snaps-registry/issues/101#issuecomment-1709438667
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue? https://github.com/MetaMask/snaps-registry/issues/101#issuecomment-1709438667
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue? https://github.com/MetaMask/snaps-registry/issues/101#issuecomment-1709438667
- [x] The corresponding pull request in this repo has been merged. https://github.com/MetaMask/snaps-registry/pull/77

**Comment by kenhkan** [comment]
Audit report: [Sayfer - 2023-08 Penetration Testing Report for AnChain Snap .pdf](https://github.com/MetaMask/snaps-registry/files/12544383/Sayfer.-.2023-08.Penetration.Testing.Report.for.AnChain.Snap.pdf)

**Comment by kenhkan** [comment]
Discovered vulnerabilities:

1. Snap Hosted Locally
2. Unexpected Success Message
3. Lack of Documentation
4. Wrong Fuction Name
5. Unused Parameter
6. Missing Unit Tests

All of the vulnerabilities are fixed as of this commit: https://github.com/AnChainAI/web3-security-snap/commit/d69cfe0cdb3f00778cba3efc996e1230d5046fef
