### ISSUE TITLE
[New Snap] Cosmos by Leap

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#103]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/leapwallet/cosmos-metamask-snap
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/@leapwallet/metamask-cosmos-snap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://github.com/MetaMask/snaps-registry/issues/103#issuecomment-1709442684
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue? https://github.com/MetaMask/snaps-registry/issues/103#issuecomment-1709442747
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue? https://github.com/MetaMask/snaps-registry/issues/103#issuecomment-1709442747
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue? https://github.com/MetaMask/snaps-registry/issues/103#issuecomment-1709442747
- [x] The corresponding pull request in this repo has been merged. https://github.com/MetaMask/snaps-registry/pull/77

**Comment by kenhkan** [comment]
Audit report: [Sayfer - 2023-08 Penetration Testing Report for LeapWallet Snap  - Updated.pdf](https://github.com/MetaMask/snaps-registry/files/12544468/Sayfer.-.2023-08.Penetration.Testing.Report.for.LeapWallet.Snap.-.Updated.pdf)

**Comment by kenhkan** [comment]
Discovered vulnerabilities:

1. No Tests Found
2. formatAllowanceOption Function is Missing a Default Case
3. tokenToString is Used Before Defined

All of the vulnerabilities are fixed. See audit report for more information.
