### ISSUE TITLE
[New Snap] Vega

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#107]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/vegaprotocol/vega-snap
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/@vegaprotocol/snap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://github.com/MetaMask/snaps-registry/issues/107#issuecomment-1709454786
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue? https://github.com/MetaMask/snaps-registry/issues/107#issuecomment-1709454848
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue? https://github.com/MetaMask/snaps-registry/issues/107#issuecomment-1709454848
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue? N/A
- [x] The corresponding pull request in this repo has been merged. https://github.com/MetaMask/snaps-registry/pull/77

**Comment by kenhkan** [comment]
Audit report: [vega_audit_final.pdf](https://github.com/MetaMask/snaps-registry/files/12544564/vega_audit_final.pdf)

**Comment by kenhkan** [comment]
Discovered vulnerabilities:

> OS-VGA-ADV-00 [med]| User Interface Message Spoofing

Fixed in commit 001e207
