### ISSUE TITLE
[New Snap] Assets Risk Detection

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#116]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/GoPlusSecurity/riskdetect-snap
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/@goplus/riskdetect-snap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://github.com/MetaMask/snaps-registry/issues/116#issuecomment-1710941933
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue? https://github.com/MetaMask/snaps-registry/issues/116#issuecomment-1710944572
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue? https://github.com/MetaMask/snaps-registry/issues/116#issuecomment-1710944572
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue? https://github.com/MetaMask/snaps-registry/issues/116#issuecomment-1710944572
- [x] The corresponding pull request in this repo has been merged. https://github.com/MetaMask/snaps-registry/pull/65

**Comment by kenhkan** [comment]
Discovered vulnerabilities:

> [N1] [Suggestion] Redundant code

Fixed; The issue has been fixed in commit: 1e4b98327e4836aa9ae26f427c6b0c03ab9102c0.

> [N2] [Suggestion] Lack of origin display

Fixed; The issue has been fixed in commit: 1e4b98327e4836aa9ae26f427c6b0c03ab9102c0.

> [N3] [Low] Arbitrary data forgery

Fixed; The issue has been fixed in commit: dead3acab6905662515aa69fdc01e274239400ba.
