### ISSUE TITLE
[New Snap] Tenderly

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#117]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/Tenderly/tenderly-snap
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/@tenderly/metamask-snap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://github.com/MetaMask/snaps-registry/issues/117#issuecomment-1710948405
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue? https://github.com/MetaMask/snaps-registry/issues/117#issuecomment-1710949102
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue? https://github.com/MetaMask/snaps-registry/issues/117#issuecomment-1710949102
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue? https://github.com/MetaMask/snaps-registry/issues/117#issuecomment-1710949102
- [x] The corresponding pull request in this repo has been merged. https://github.com/MetaMask/snaps-registry/pull/65

**Comment by kenhkan** [comment]
Audit report: [2023-08 Metamask Snap PT for Tenderly.pdf](https://github.com/MetaMask/snaps-registry/files/12554568/2023-08.Metamask.Snap.PT.for.Tenderly.pdf)

**Comment by kenhkan** [comment]
Discovered vulnerabilities:

1. Unused Functions
2. Misleading Error Message

Both vulnerabilities have been verified by the original auditor and fixed as of https://github.com/Tenderly/tenderly-snap/pull/1/commits/a649e4cb9547a5159a3e1b0bd9f684419bd4b337
