### ISSUE TITLE
[New Snap] Saferoot

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#118]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/Staging-Labs/Saferoot-Snap
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/saferoot-metamask-snap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://github.com/MetaMask/snaps-registry/issues/118#issuecomment-1710958427
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue? https://github.com/MetaMask/snaps-registry/issues/118#issuecomment-1710962409
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue? https://github.com/MetaMask/snaps-registry/issues/118#issuecomment-1710962409
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue? https://github.com/MetaMask/snaps-registry/issues/118#issuecomment-1710962409
- [ ] The corresponding pull request in this repo has been merged.

**Comment by kenhkan** [comment]
Audit report: [Least Authority- Staging Labs Saferoot Snap Final Audit Report (1).pdf](https://github.com/MetaMask/snaps-registry/files/12554653/Least.Authority-.Staging.Labs.Saferoot.Snap.Final.Audit.Report.1.pdf)

**Comment by kenhkan** [comment]
Discovered vulnerabilities:

1. Issue A: Data Is Stored Unencrypted in localstorage
2. Issue B: Usage of Vulnerable Dependencies
3. Suggestion 1: Improve Error Handling and Reporting
4. Suggestion 2: Update Deprecated Functions
5. Suggestion 3: Adhere to MetaMask Best Practices
6. Suggestion 4: Remove Unused Code
7. Suggestion 5: Improve Code Comments

All vulnerabilities have been fixed and verified according to the original auditor.
