### ISSUE TITLE
[New Snap] Threat Intel

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#122]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/demystify-network/ThreatIntelligence
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/threat-intel-snap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://github.com/MetaMask/snaps-registry/issues/122#issuecomment-1710988729
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue? https://github.com/MetaMask/snaps-registry/issues/122#issuecomment-1710989707
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue? https://github.com/MetaMask/snaps-registry/issues/122#issuecomment-1710989707
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue? https://github.com/MetaMask/snaps-registry/issues/122#issuecomment-1710989707
- [x] The corresponding pull request in this repo has been merged. https://github.com/MetaMask/snaps-registry/pull/55

**Comment by kenhkan** [comment]
Audit report: [2023-08 Metamask Snap PT for Demystify-4.pdf](https://github.com/MetaMask/snaps-registry/files/12554895/2023-08.Metamask.Snap.PT.for.Demystify-4.pdf)

**Comment by kenhkan** [comment]
Discovered vulnerabilities:

1. Incorrect Risk Score Calculation
2. Usage of Encoded Hardcoded Values Without Description
3. Usage of Confusing “Magic Numbers”

All vulnerabilities have been fixed and verified by the original auditor. Refer to the audit report for details.
