### ISSUE TITLE
[New Snap] Algorand Wallet

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#124]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/algorandfoundation/algo-metamask
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/@algorandfoundation/algorand-metamask-snap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://github.com/MetaMask/snaps-registry/issues/124#issuecomment-1711010749
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue? https://github.com/MetaMask/snaps-registry/issues/124#issuecomment-1711011320
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue? https://github.com/MetaMask/snaps-registry/issues/124#issuecomment-1711011320
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue? https://github.com/MetaMask/snaps-registry/issues/124#issuecomment-1711011320
- [x] The corresponding pull request in this repo has been merged. https://github.com/MetaMask/snaps-registry/pull/43

**Comment by kenhkan** [comment]
Audit report: [algorand_snapalgo_audit_final.pdf](https://github.com/MetaMask/snaps-registry/files/12555138/algorand_snapalgo_audit_final.pdf)

**Comment by kenhkan** [comment]
Discovered vulnerabilities:

> OS-SNP-ADV-00 [med]| Insecure Encryption On Seed

Fixed in 81414a9
