### ISSUE TITLE
[New Snap] app.walletchat.fun

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#84]
A Snap needs to satisfy all items in the list below, with 1 approval from someone on the MetaMask Snaps team.

- [x] Is the Snap repository publicly accessible? https://github.com/Wallet-Chat/walletchat-metamask-snap
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/)? https://www.npmjs.com/package/walletchat-metamask-snap
- [x] Has an approved third-party audit been performed and the original audit report attached to this issue? https://github.com/MetaMask/snaps-registry/issues/84#issuecomment-1708728256
- [x] Has a complete list of discovered vulnerabilities from the audit report presented in this issue? Yes
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue? https://github.com/MetaMask/snaps-registry/issues/84#issuecomment-1708734766
- [x] For vulnerabilities that have been deemed not necessary to be addresses, is there reason to each of them documented in this issue? https://github.com/MetaMask/snaps-registry/issues/84#issuecomment-1708734766
- [x] The corresponding pull request in this repo has been merged. https://github.com/MetaMask/snaps-registry/pull/43/files

**Comment by kenhkan** [comment]
Audit performed by Cure53

[WalletChat-WAC-01-report.pdf](https://github.com/MetaMask/snaps-registry/files/12540321/WalletChat-WAC-01-report.pdf)
