### ISSUE TITLE
[New Snap] ETHSign Keychain

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#98]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/EthSign/keychain-snap
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/keychain-snap?activeTab=readme
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://github.com/MetaMask/snaps-registry/issues/98#issuecomment-1709408548
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue? https://github.com/MetaMask/snaps-registry/issues/98#issuecomment-1709411152
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue? https://github.com/MetaMask/snaps-registry/issues/98#issuecomment-1709411152
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue? https://github.com/MetaMask/snaps-registry/issues/98#issuecomment-1709411152
- [ ] The corresponding pull request in this repo has been merged.

**Comment by kenhkan** [comment]
Audit report: [ethsign_keychain_audit_final.pdf](https://github.com/MetaMask/snaps-registry/files/12544220/ethsign_keychain_audit_final.pdf)

**Comment by kenhkan** [comment]
Discovered vulnerabilities:

> OS-ETH-ADV-00 [med] | Insecure Signature-Based Authorization

Fixed in commit 3716c36. See audit report for details.

> OS-ETH-ADV-01 [med] | Insecure Encryption

Fixed in 8d59cf4. See audit report for details.

> OS-ETH-ADV-02 [low] | Denial Of Service Via Batching

Fixed by introducing a patch on the back-end server, which is now rate-limited by one request per seven seconds and has a batch limit. See audit report for details.

> OS-ETH-SUG-00 | GraphQL Injection

Informational only. Not addressed.

> OS-ETH-SUG-01 | Vulnerable NPM Packages

Informational only. Not addressed.

> OS-ETH-SUG-02 | Validate Remote Procedure Call Parameters

Informational only. Not addressed.

> OS-ETH-SUG-03 | Information Disclosure Via Errors

Informational only. Not addressed.
